### ISSUE TITLE
Using System.normalize instead of location.origin

### ISSUE THREAD

**Issue by guybedford** [capaj/jspm-hot-reloader#1]
The reload logic looks solid here, which was really great to see.

The weak point in https://github.com/capaj/jspm-hot-reloader/blob/master/jspm-hot-reloader.js#L13 is that you probably want to be using `System.normalize`, as that will cover all path rules etc. There is also `normalizeSync`, but `normalize` is probably preferable to support say plugins as well.

**Comment by capaj** [comment]
@guybedford thanks, this is exactly the feedback I needed. I've been using SystemJS for some time and of course I know this method, but in the excitement I forgot about it.

**Comment by capaj** [comment]
@guybedford  done in https://github.com/capaj/jspm-hot-reloader/commit/f031a8b44b7425a32c889bb2f0186cef29d68873

**Comment by guybedford** [comment]
:+1:
