### ISSUE TITLE
Clarify perserving state?

### ISSUE THREAD

**Issue by peteruithoven** [capaj/jspm-hot-reloader#11]
From the readme:
> If a match is found, we then aggressively delete the changed module and recursively all modules which import it directly or indirectly via other modules. 

I'm probably missing something easy but this seems to mean it will reload everything? It will not only reload the changed module, but even the first module that imported the module indirectly. Could you clarify where one should keep it's state?
Running the [JSPM-React](https://github.com/capaj/jspm-react/) for example, when changing `stateles-sample.js` it also deletes and reloads `app.js`. 
I'd like to use this with Redux, which has a separate logic-less store, but if even the root javascript file is deleted and reloaded so will that stored state.

**Comment by capaj** [comment]
let's say you need a state which gets preserved in `stateles-sample.js`.
1. create a `my-awesome.state.js` file anywhere in public. It can look like:
```
export default {
   awesome: true
}
```
2. import `my-awesome-state.js` into `stateles-sample.js`
3. now whenever you change awesome: to any other value and make a change in  `stateles-sample.js` your value will be preverved throught hot reload

So to sum it up, in order to preserve state, you need to have it in separate module.

**Comment by peteruithoven** [comment]
But this only applies to state stored per component? What about a more global app state? 
If I add this `my-awesome.state.js` to the root javascript file (`app.js` in the case of the [JSPM-React](https://github.com/capaj/jspm-react/) example) it will be reloaded and the state is lost right?

**Comment by capaj** [comment]
No, it applies generally to any module. It won't reload even if it is a dependency of app.js. Assuming you're making changes in stateless-sample.js.
When you make changes in the state module itself then yes, your state won't be preserved.

Also who says, that your `my-awesome.state.js` can't contain state for the whole app? Surely it can.

**Comment by peteruithoven** [comment]
Ah I understand it now. Thanks for your clarification. The important detail that I missed is that you need to create that state in a separate model. Having a State class module that's important and initiated in the root javascript folder won't work. 

I made an very very minimal example:
https://github.com/peteruithoven/jspm-hot-reloader-example
Maybe it clarifies things for other people.
