### ISSUE TITLE
Doesn't work with React Router

### ISSUE THREAD

**Issue by elliotlings** [capaj/jspm-hot-reloader#13]
It doesn't seem to work with React Router. It reloads the modules put the page doesn't update.

**Comment by peteruithoven** [comment]
Would be useful to point to a example?

**Comment by elliotlings** [comment]
main.js
```jsx
import styles from './css/main.css!';
import React from 'react';
import { render } from 'react-dom';
import { Router, Route, Link } from 'react-router';

import Nav from "./components/Nav";
import About from "./components/About";

class App extends React.Component {
  render() {
    return (
      <div>
        <Nav />
        <div className="page">
            {this.props.children}
        </div>
      </div>
    )
  }
}

class NoMatch extends React.Component {
    render() {
        return (
            <p>Could not find page.</p>
        )
    }
}

render((
    <Router>
        <Route path="/" component={App}>
            <Route path="about" component={About} />
            <Route path="*" component={NoMatch}/>
        </Route>
    </Router>
), document.getElementById('app'))
```

about.js
```jsx
import React from 'react';
import { Router, Route, Link } from 'react-router'

export default class About extends React.Component {
    render() {
        return (
            <h1>About</h1>
        )
    }
}
```

When you go to /about the first time you see the 'About' header.
If I changed About to About Us, while it's downloading the about.js file again, the DOM doesn't change.

**Comment by capaj** [comment]
@elliotlings I am 100% sure it works for react-router when I have my console opened. When I close it, I am not so 100% sure.
I think this might very well be related to: https://github.com/indexzero/http-server/issues/149

**Comment by elliotlings** [comment]
Before I started using react-router modules would reload fine but since I put in react-router (and now I'm using redux-router) it doesn't seem to reload them.

I am using https://github.com/tj/serve along with https://github.com/capaj/chokidar-socket-emitter.

**Comment by guybedford** [comment]
This may just be a result of needing to handle unloading react router and then reloading it?

**Comment by jackfranklin** [comment]
@elliotlings I'm using React Router just fine in my app, you can see the code changes I had to make to add jspm-hot-reloader into this app in this PR: https://github.com/jackfranklin/interactive-es6/pull/3

You have to create a pseudo wrapper that will always rerender to make sure it updates properly, as per: https://github.com/capaj/jspm-react/blob/master/public/app.js

**Comment by elliotlings** [comment]
@jackfranklin Thank you! That works perfectly!

**Comment by capaj** [comment]
@jackfranklin thanks a lot fro resolving this instead of me!

**Comment by pedramphp** [comment]
@jackfranklin you are the man. I also got it working.

**Comment by danfma** [comment]
@jackfranklin thanks!
