### ISSUE TITLE
goes into infinite loop on cyclic dependencies

### ISSUE THREAD

**Issue by capaj** [capaj/jspm-hot-reloader#15]
we should at least put up a guard to prevent that

**Comment by guybedford** [comment]
There's no reason not to support cyclic dependencies, and in most cases detecting them is no more complex than supporting them. If there's anyway I can help just let me know.

**Comment by capaj** [comment]
@guybedford totally agree. I was planning to just add one if statement, which would jump out of the recursion. That should fix it, right?

**Comment by guybedford** [comment]
Yes exactly, circular references are usually handled by carrying the list of seen modules down the tree visitor, and stopping when they come up again.
