### ISSUE TITLE
Unload hook

### ISSUE THREAD

**Issue by guybedford** [capaj/jspm-hot-reloader#2]
In order to support things like CSS unloading, or unloading modules that have side effects or events already applied to the DOM, it is probably necessary to implement some special export as an unload hook regardless.

**Comment by capaj** [comment]
@guybedford yeah, that is exactly why it is working so good with react-react apps usually don't have side effects.
this export could be defined by plugins right- so for example CSS plugin would export a module with unload hook which I would call when deleting a module.

**Comment by guybedford** [comment]
Yes exactly, something like like `export function __unload` could be inlined by plugins although the export would still be on the final module itself, so I could use it equally in my app module to support hot-reloading, even though it isn't loaded via a plugin.

**Comment by capaj** [comment]
fixed with https://github.com/capaj/jspm-hot-reloader/commit/c60a0d1cc9365cb9c4f3f0dd08fa151814b39dd2

**Comment by guybedford** [comment]
:+1:
