### ISSUE TITLE
TypeError: Cannot convert undefined or null to object (System.loads undefined)

### ISSUE THREAD

**Issue by jackfranklin** [capaj/jspm-hot-reloader#20]
I'm getting the above error on this line:

```js
Object.keys(moduleMap).forEach((moduleName) => {
```

This error is coming from the fact that `moduleMap` is undefined, and the reason for this is that `System.loads` is undefined.

I'm on SystemJS 0.19.5 standard, and can't see anything else that would be causing this, nothing obvious at all. What is System.loads expected to contain?

**Comment by johnraz** [comment]
isn't this one fixed by #21  ?

**Comment by jackfranklin** [comment]
@johnraz yeah :)
