### ISSUE TITLE
Putting System.trace into constructor doesn't work

### ISSUE THREAD

**Issue by jackfranklin** [capaj/jspm-hot-reloader#25]
My previous PR that moved `System.trace = true` into the constructor doesn't work, it seems. Similarly even setting `System.trace = true` in the top level of `jspm-hot-reloader.js` doesn't work. I had to add it to my HTML again.

I'm not entirely sure why - my guess is that `System.trace` needs to be set before System ever imports anything?

**Comment by jackfranklin** [comment]
Not that the behaviour differs too:

- If `System.trace = true` in the __constructor__ you get an error as `System.loads` is undefined.
- if `System.trace = true` is in the root of the file, you don't get an error but nothing hot reloads.
- Moving `System.trace = true` into the top line of the `script` tag in `index.html` gets everything working.

**Comment by guybedford** [comment]
Yes `System.trace` must be set before the first `System.import` statement.

**Comment by jackfranklin** [comment]
Perfect, thanks for clarifying. PR incoming!

**Comment by capaj** [comment]
@guybedford thought so. 
@jackfranklin  no need for that, will fix that myself.
