### ISSUE TITLE
Rename project to systemjs-hot-reloader?

### ISSUE THREAD

**Issue by guybedford** [capaj/jspm-hot-reloader#27]
There doesn't seem to be anything jspm-specific here as far as I can tell?

Some of the Angular workflows are now focusing on SystemJS-only projects, which would benefit a lot from this project. If it's as simple as a rename so we can include it in the SystemJS docs that would be a nice thing to offer.

**Comment by capaj** [comment]
@guybedford  yeah, good idea. When I started I didn't really know what this will become.

**Comment by guybedford** [comment]
@capaj thanks for considering!
